### ISSUE TITLE
ERROR when executing the script

### ISSUE THREAD

**Issue by gelatorema** [DiegoCaraballo/Email-extractor#15]
when ever i run the script it says "Line 6 in module, from googlesearch import search import error no module named googlesearch

**Comment by vebaev** [comment]
Same here...

**Comment by DiegoCaraballo** [comment]
@gelatorema @vebaev 
Try with: pip install requirements.txt

**Comment by darkhacknet** [comment]
> when ever i run the script it says "Line 6 in module, from googlesearch import search import error no module named googlesearch

Brother. You must install the requirements one by one, with pip command, and then just run the script, but take in count the version of python that you have installed, if you are using python3, use it as command to run the script. And you will see that works like a charm ! ;)

**Comment by pitufogranjero** [comment]
I have an error

**'utf-8' codec can't decode byte 0xf3 in position 217: invalid continuation byte**

**Comment by drebeat** [comment]
After installing all the requirement.txt i get the following error:
- Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "C:\Users\holam\AppData\Local\Programs\Python\Python310\lib\site-packages\fake_useragent\utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
-   File "C:\Users\holam\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:
